server:
  port: 8081

spring:
  application:
    name: external-odds-provider
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
app:
  rabbitmq:
    queue-name: odds-changes.queue
    exchange-name: odds-changes.exchange
    routing-key: odds.change

logging:
  level:
    sun:
      rmi:
        transport:
          tcp: OFF
