server:
  port: 8080

spring:
  application:
    name: odds-consumer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        # With AUTO, if processing crashes after Spring ACKs but before you finish processing, message is lost forever
        # With MANUAL, you ACK only after successful processing → if it crashes, RabbitMQ redelivers
        # Gives you control over basicNack + dead-letter routing on failure
        acknowledge-mode: manual
        prefetch: 250
        concurrency: 1

app:
  rabbitmq:
    queue-name: odds-changes.queue
    exchange-name: odds-changes.exchange
    routing-key: odds.change
  external-api:
    base-url: http://localhost:8082/api/validator

logging:
  level:
    sun:
      rmi:
        transport:
          tcp: OFF
