server:
  port: 8080

spring:
  application:
    name: odds-consumer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        # With AUTO, if processing crashes after Spring ACKs but before you finish processing, message is lost forever
        # With MANUAL, you ACK only after successful processing → if it crashes, RabbitMQ redelivers
        # Gives you control over basicNack + dead-letter routing on failure
        acknowledge-mode: manual
        prefetch: 250
        concurrency: 1

  datasource:
    url: jdbc:h2:file:/tmp/oddsdb;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        type: trace
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

app:
  rabbitmq:
    queue-name: odds-changes.queue
    exchange-name: odds-changes.exchange
    routing-key: odds.change
    dlx-name: odds-changes.dlx
    dlq-name: odds-changes.dlq
    dlq-routing-key: odds.change.dlq
  external-api:
    base-url: http://localhost:8082/api/validator
  worker:
    pool:
      size: 10
  cache:
    type: caffeine # or redis
    message-id:
      duration-minutes: 10
      max-size: 10000

logging:
  level:
    sun:
      rmi:
        transport:
          tcp: OFF
